version: "3"
services:
  recognition_service:
    env_file:
      - speech_service_config.env
    restart: always
    ports:
      - "80"
    build: ./SpeechRecognitionService
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"

  recognition_bot:
    env_file:
      - bot_config.env
    build: ./recognition_bot
    restart: always
    volumes:
      - ~/.recognition_db/:/db
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"
